CREATE TABLE modernBoard (
    id          NUMBER  PRIMARY KEY, -- 자동 증가 ID
    category    VARCHAR2(50) NOT NULL,                               -- 카테고리
    title       VARCHAR2(200) NOT NULL,                              -- 제목
    content     CLOB,                                                -- 내용 (긴 텍스트)
    member_id   NUMBER NOT NULL,                               -- 작성자
    created_at  DATE DEFAULT SYSDATE,
	DEL_YN CHAR(1) DEFAULT 'N'               -- 작성일
);

--오라클 11g에서
CREATE SEQUENCE SEQ_Md_id START WITH 1 INCREMENT BY 1;

CREATE TABLE MODERNBOARD_COMMENT(
	ID NUMBER PRIMARY KEY,
	BOARD_ID NUMBER NOT NULL,
	PARENT_ID NUMBER,
	CONTENT VARCHAR2(500),
	MEMBER_ID NUMBER NOT NULL,
	DEL_YN CHAR(1) DEFAULT 'N',
	CREATED_AT DATE DEFAULT SYSDATE
)

CREATE SEQUENCE SEQ_COMMENT_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE modernboard_file(
	ID NUMBER PRIMARY KEY,
	BOARD_ID NUMBER NOT NULL,
	ORIGINAL_NAME VARCHAR2(255) NOT NULL,
	SAVED_NAME VARCHAR2(255) NOT NULL,
	FILE_PATH VARCHAR2(500) NOT NULL,
	FILE_SIZE NUMBER NOT NULL,
	DEL_YN CHAR(1) DEFAULT 'N',
	CREATED_AT DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_FILE_ID START WITH 1 INCREMENT BY 1;

CREATE INDEX IDX_FILE_BOARD_ID ON MODERNBOARD_FILE(BOARD_ID);

CREATE TABLE MODERNBOARD_MEMBER(
	ID NUMBER PRIMARY KEY,
	EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	NAME VARCHAR2(50) NOT NULL,
	NICKNAME VARCHAR2(50) NOT NULL UNIQUE,
	PASSWORD VARCHAR2(255),
	SNS_ID VARCHAR2(255),
	SNS_TYPE VARCHAR2(20) DEFAULT 'LOCAL',
	ROLE VARCHAR2(20) DEFAULT 'ROLE_USER' NOT NULL,
	REG_DATE DATE DEFAULT SYSDATE,
	MOD_DATE DATE DEFAULT SYSDATE,
	REFRESH_TOKEN VARCHAR2(255),
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL,
	LAST_LOGIN_DATE DATE
);

CREATE SEQUENCE SEQ_MEMBER_ID START WITH 1 INCREMENT BY 1;

ALTER TABLE MODERNBOARD_MEMBER ADD CONSTRAINT CHK_MEMBER_ROLE 
CHECK (ROLE IN ('USER', 'ADMIN', 'MANAGER'));